{{- if not .Values.amt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "node-watchdog.fullname" . }}-amt
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "node-watchdog.labels" . | nindent 4 }}
type: Opaque
stringData:
  AMT_USERNAME: {{ .Values.amt.username | quote }}
  AMT_PASSWORD: {{ .Values.amt.password | quote }}
{{- end }}
